-- 0010_memories.up.sql — per-user long-term memory table
-- (plan 1791267136806, §1.3).
--
-- Reversed by `0010_memories.down.sql`; keep the two siblings in
-- sync (sqlx 0.8.6 pairs them via the
-- `<version>_<name>.up.sql` / `<version>_<name>.down.sql` filename
-- convention).
--
-- One row per `(user, subject, predicate, value)` fact. `value` and
-- `notes` are AES-256-GCM ciphertext (12-byte nonce stored in the
-- matching `_nonce` column); the encryption key is server-side,
-- loaded from `[auth.credentials].key` at boot, and never reaches
-- this DB. The taxonomy columns (`subject`, `predicate`, `tags`)
-- remain plaintext so the recall query can stay a `WHERE …
-- LIKE …` index scan without per-row decryption
-- (plan §1.2 — documented taxonomy-leak tradeoff).
--
-- Column shape:
--   id                 TEXT PK (UUIDv4, generated by the Rust code)
--   user_id            TEXT NOT NULL → users.id (CASCADE delete)
--   subject            TEXT NOT NULL  — categorical key (e.g. "doctor")
--   predicate          TEXT NOT NULL  — categorical key (e.g. "name")
--   value_nonce        BLOB NOT NULL  — 12 bytes (enforced in Rust)
--   value_ciphertext    BLOB NOT NULL  — AES-GCM output incl. 16-byte tag
--   notes_nonce        BLOB           NULL when no notes attached
--   notes_ciphertext    BLOB           NULL when no notes attached
--   tags               TEXT NOT NULL DEFAULT '' — comma-separated
--   confidence         REAL NOT NULL DEFAULT 1.0
--   source_session_id  TEXT           — nullable, sessions are short-lived
--   source_kind        TEXT NOT NULL DEFAULT 'user_stated'
--                              ('user_stated' | 'llm_inferred')
--   created_at         TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
--   last_used_at       TEXT           — bumped on every recall hit
--   expires_at         TEXT            — optional TTL for stale facts
--
-- Portability notes (mirrors `0002_credentials.up.sql`):
--   * `TEXT PRIMARY KEY` for UUID columns works on both sqlite and
--   postgres (stored as TEXT, not the native `uuid` type).
--   * `BLOB` for binary columns becomes `bytea` on postgres and
--   stays `BLOB` on sqlite — sqlx maps the two transparently.
--   * `CURRENT_TIMESTAMP` is the default for every timestamp column.
--   Both engines return a string in the same RFC 3339-like form so
--   the Rust parser (`parse_rfc3339`) does not have to branch on
--   the engine.
--
-- Index choice:
--   * `memories_user_id_idx` — single-column index for the
--   "list metadata for this user" query (`GET /api/memories`,
--   `memory_list`).
--   * `memories_user_subject_idx` /
--   `memories_user_predicate_idx` — composite indexes that drive
--   the `WHERE user_id = ? AND subject LIKE ?` / `predicate LIKE ?`
--   filters of the recall query (plan §1.4).
--   * `memories_user_last_used_idx` — composite index on
--   `(user_id, last_used_at DESC)`; the recall query orders by
--   `confidence DESC, last_used_at DESC NULLS LAST` so the
--   secondary sort also benefits.

CREATE TABLE memories (
    id                  TEXT PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    subject             TEXT NOT NULL,
    predicate           TEXT NOT NULL,
    value_nonce         BLOB NOT NULL,
    value_ciphertext     BLOB NOT NULL,
    notes_nonce         BLOB,
    notes_ciphertext     BLOB,
    tags                TEXT NOT NULL DEFAULT '',
    confidence          REAL NOT NULL DEFAULT 1.0,
    source_session_id   TEXT,
    source_kind         TEXT NOT NULL DEFAULT 'user_stated',
    created_at          TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at        TEXT,
    expires_at          TEXT
);

CREATE INDEX memories_user_id_idx
    ON memories(user_id);
CREATE INDEX memories_user_subject_idx
    ON memories(user_id, subject);
CREATE INDEX memories_user_predicate_idx
    ON memories(user_id, predicate);
CREATE INDEX memories_user_last_used_idx
    ON memories(user_id, last_used_at DESC);